### ISSUE TITLE
quick-demo exits after first call complete

### ISSUE THREAD

**Issue by john-** [ZhongHuaRong/LinPhone-Qt-Demo#2]
For me quick-demo exits after the first call made or receive completes.  I see this in the log after I select hang up button.

Is this the intended behavior?   desktop-demo does not act this way (it stays open for another call).

If it should not operate this way here is what is on the console when hangup occurs:

2021-10-06 13:47:59:421 mediastreamer-warning-ms_filter_remove_notify_callback(filter=0x293c180): no registered callback with fn=0x7fc1792871a0 and ud=0x2615e50
0
13:48:00: The program has unexpectedly finished.
13:48:00: The process was ended forcefully.
13:48:00: /usr/local/src/LinPhone-Qt-Demo/Debug/quick-demo crashed.

**Comment by ZhongHuaRong** [comment]
Sorry, this is the code I added when debugging, and I forgot to cancel it. Code updated

When you hang up, you need to pay attention, you need to close the video display before the linphone::Call object is destructed (the Camera class needs to be deleted), otherwise it will crash

**Comment by john-** [comment]
Thanks for confirming.  I will keep what you say about the Camera class in mind.

**Comment by ZhongHuaRong** [comment]
Hahaha, these qInfo are used for debugging, no security check is added, you can comment out or add pointer validity judgment at will
