### ISSUE TITLE
quick-demo incoming video call

### ISSUE THREAD

**Issue by john-** [ZhongHuaRong/LinPhone-Qt-Demo#3]
For me when incoming video call is answered by quick-demo video is transmitted to the remote end (Android in this case) however the quick-demo application does not show either the remote end video or what is captured by the local camera.

If I add a button to toggle the state of loader1 I can get video by disabling loader1 and then re-enable it.  This is done while call is in progress.

```
Button {
    text: loader1.active
    onClicked: loader1.active = !loader1.active
 }
```

Based on this it may be a timing issue.    This does not occur with desktop-demo.

Any idea what this could be?

**Comment by ZhongHuaRong** [comment]
After my observation, the order of linphone::Call::State may change
The order of status changes in this demo is: IncomingReceived->Connected->StreamsRunning
And I tested it in other projects: Connected->StreamsRunning->IncomingReceived

I need to spend time to research later
